---
title: "Trains"
author: "Jessica Wu"
date: "3/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gov.1005.data)
library(tidyverse)
library(infer)
```

```{r}

# filter for just ppl who have been treated
train %>%
  filter(treatment == "Treated") %>%
  
# bootstrap sample with same initial size of sample which is 51
  
  rep_sample_n(size = 51, replace = TRUE, reps = 1000) %>%
  summarize(avg_inc = mean(income)) %>%
  
# calculating the 95% CI using the percentile method
  
  pull(avg_inc) %>%
  quantile(c(0.025, 0.975))

```

We are 95% confident that the average income of Bostonians commuters who heard people speaking Spanish on the platform is between $115,630 and $153,489

```{r}
# looking for mean income of the treated and the control, then the difference 
# between the two
train %>%
  group_by(treatment) %>%
  summarize(avg_inc = mean(income)) %>%
  pivot_wider(names_from = treatment, values_from = avg_inc) %>%
  mutate(inc_diff = Treated - Control)

```


